### ISSUE TITLE
working on Raspberry Pi 3 /4?

### ISSUE THREAD

**Issue by Eduardo-F** [Mictronics/pluto-gps-sim#12]
Hi,
I have installed pluto-gps-sim in a laptop and works very fine.

Now I tried to run it on a Rasperry Pi 4 (and Pi 3 also) then apparently works but my ublox GPS receiver never fix (never gets a SAT in green), It seems like messages (or RF signal) are not continuous.
Any idea?
Thank you.

**Comment by Eduardo-F** [comment]
image

**Comment by Eduardo-F** [comment]
I checked it with a spectrum analyzer and the RF signal is not continuous, it is "blinking"

**Comment by Eduardo-F** [comment]
![2020-10-13-134201_1920x1080_scrot](https://user-images.githubusercontent.com/35740465/95856309-1d9d5500-0d5a-11eb-8d9f-85ebfd5be25c.png)

**Comment by Eduardo-F** [comment]
Resources in use are only  27%
Any idea about why pluto-gps-sim running fine bat generated RF signal is wrong?

Any idea will be appreciate very much

**Comment by SpontaneousDuck** [comment]
I also am seeing this same issue but on a full computer with and Intel i7. Investigating

**Comment by Eduardo-F** [comment]
Hi SpontaneousDuck,
pluto-sdr-sim runs fine on my laptop (intel i3).
Furthermore, I can run it on a raspberry pi 4 with 4GB RAM, WITH overclocking.

**Comment by fpgasdr** [comment]
in my case in the raspberry pi was not working, the pluto-sdr-sim task is running at 100% and the spectrum was interrupting due the cpu is not fast enough.

for the raspberry pi4 it seems the same but didn't tried with overclocking. how much overclock is needed?.

**Comment by Eduardo-F** [comment]
In config.txt file I add:
over_voltage=4
arm_freq=2000

**Comment by Mictronics** [comment]
Project closed.
