### ISSUE TITLE
 Unable to find host: Name or service not known

### ISSUE THREAD

**Issue by fpgasdr** [Mictronics/pluto-gps-sim#2]
hello,
my pluto device is connected with an usb to ethernet adapter to my network and the command iio_info -u ip:172.31.110.221 answer correctly with all the device information(also the -n option).
but the command ./pluto-gps-sim -e brdc3540.14n -u ip:172.31.110.221 doesn't. it says:
ERROR: Unable to find host: Name or service not known
Failed creating IIO context: No such file or directory

what I'm doing wrong?.

**Comment by Mictronics** [comment]
Try the -n option. (without "ip:")

```
-u <uri> ADALM-Pluto URI
-n <network> ADALM-Pluto network IP or hostname (default pluto.local)
```

**Comment by fpgasdr** [comment]
thanks,
it worked with the -N flag but not -n ¿?

**Comment by Mictronics** [comment]
Fixed the usage output for -U and -N.
