### ISSUE TITLE
GPS-signal just getting jammed, no new location

### ISSUE THREAD

**Issue by Narhog** [Mictronics/pluto-gps-sim#4]
I just tried to generate a Spoofing signal via
`./pluto-gps-sim -e brdc3250.19n -l 39.028225,125.751300,100 -U usb:1.4.5`
The GPS-Connection of my mobile phone just drops but i don't get a new location.
What did I do wrong?

**Comment by Narhog** [comment]
Ok, the regular gps-signal doesn't get jammed by setting attenuation to -55.0
But i still don't get the location i wanted

**Comment by Mictronics** [comment]
Are you aware that on modern mobile device GPS is only one of several services to obtain the device location. Also, real GPS has very low guaranteed signal strength everywhere on earth. Even the -55dBm are well above that level. Your phone my include jamming detection by strong signals and therefore doesn't consider the Pluto signal being valid.
