### ISSUE TITLE
make all can't work

### ISSUE THREAD

**Issue by szakacsm** [Mictronics/pluto-gps-sim#5]
~$ git clone https://github.com/mictronics/pluto-gps-sim
Cloning into 'pluto-gps-sim'...
remote: Enumerating objects: 88, done.
remote: Total 88 (delta 0), reused 0 (delta 0), pack-reused 88
Unpacking objects: 100% (88/88), done.
~$ cd pluto-gps-sim/
~/pluto-gps-sim$ make all
cc  -std=c11 -O2 -g -W -Wall -D_GNU_SOURCE -I/usr/local/include -c plutogpssim.c -o plutogpssim.o
plutogpssim.c:22:10: fatal error: curl/curl.h: Nincs ilyen fájl vagy könyvtár
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:10: plutogpssim.o] Error 1

what can be the problem?

**Comment by Mictronics** [comment]
> Nincs ilyen fájl vagy könyvtár
libcurl dev package not installed? Don't know what OS you are on.

**Comment by szakacsm** [comment]
Debian
libcurl dev already intalled
