### ISSUE TITLE
PPS test

### ISSUE THREAD

**Issue by Eduardo-F** [Mictronics/pluto-gps-sim#8]
Hello, 

I have done some "time" testing.

The test consists of compare the PPS (pulse per second) generate by a receiver with real Sats signal vs a PPS generated by a receiver with signal generated by Pluto simulator.
I measured the time between both PPS signals and the result is that PPS generated by Pluto is delayed about 10 microsec every second.
I try to explain me:
t0: both PPS pulses are at same time
t1 (1 second later from t0): Pluto PPS is delayed 10 microsec from real PPS
t2 (1 second later from t1): Pluto PPS is delayed 20 microsec from real PPS
t3 (1 second later from t2): Pluto PPS is delayed 30 microsec from real PPS
...
So, at 100 seconds from t0, Pluto PPS is delayed 1000 microsec from real PPS.

Do you know what could be the delay cause?
frames length?
time between messages?

Could you help me to fix it?
Thank you so much

**Comment by Eduardo-F** [comment]
IvanKor (from gps-sdr-sim project) about my question says:
"this is the accuracy of setting the frequency of the crystal oscillator"
"incGpsTime not real time, real time stream in Pluto-SDR"

so, I think following lines are involved in that IvanKor says and they control the data stream to PlutoSDR, but i don't understand how they work:
pthread_cond_signal(&plutotx.data_cond);
pthread_cond_wait(&plutotx.data_cond, &plutotx.data_mutex);
pthread_mutex_unlock(&plutotx.data_mutex); 

Maybe modifing the data stream speed can compensate or improve the final 10 microseconds PPS delay?
Any idea about how the data stream speed can be modify?

Thank you

**Comment by Mictronics** [comment]
The program is running two threads. One main thread, doing the calculations and IQ data generation. Second thread is feeding the PlutoSDR from IQ buffer. Since both threads share common IQ data buffer the commands you mention are there for inter thread signaling to avoid overlapping buffer access.
https://linux.die.net/man/3/pthread_cond_signal 
https://linux.die.net/man/3/pthread_cond_wait
https://linux.die.net/man/3/pthread_mutex_unlock

Streaming speed is not a problem here. If it would be the case the RF signal is disturbed and produces no longer something a GPS would receive.

**Comment by Eduardo-F** [comment]
Thank you very much for your support.
Your program is running very good with my GPS receivers, even with smart phones.
However in long time tests the PPS is constantly delayed about 10 microseconds per second, this is what I would like to improve.

I also did this test with gps-sdr-sim and its PPS delay is about 1 microsecond per second.

**Comment by Eduardo-F** [comment]
Thank you very much for your support.
Your program is running very good with my GPS receivers, even with smart phones.
However in long time tests the PPS is constantly delayed about 10 microseconds per second, this is what I would like to improve.

I also did this test with gps-sdr-sim and its PPS delay is about 1 microsecond per second.

**Comment by Eduardo-F** [comment]
Then, any idea about how to reduce or correcting the PPS delay?
